// Generated by gencpp from file plumbing_pub_sub_doublemsg/pose1.msg
// DO NOT EDIT!


#ifndef PLUMBING_PUB_SUB_DOUBLEMSG_MESSAGE_POSE1_H
#define PLUMBING_PUB_SUB_DOUBLEMSG_MESSAGE_POSE1_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace plumbing_pub_sub_doublemsg
{
template <class ContainerAllocator>
struct pose1_
{
  typedef pose1_<ContainerAllocator> Type;

  pose1_()
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  pose1_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::plumbing_pub_sub_doublemsg::pose1_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::plumbing_pub_sub_doublemsg::pose1_<ContainerAllocator> const> ConstPtr;

}; // struct pose1_

typedef ::plumbing_pub_sub_doublemsg::pose1_<std::allocator<void> > pose1;

typedef boost::shared_ptr< ::plumbing_pub_sub_doublemsg::pose1 > pose1Ptr;
typedef boost::shared_ptr< ::plumbing_pub_sub_doublemsg::pose1 const> pose1ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::plumbing_pub_sub_doublemsg::pose1_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::plumbing_pub_sub_doublemsg::pose1_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::plumbing_pub_sub_doublemsg::pose1_<ContainerAllocator1> & lhs, const ::plumbing_pub_sub_doublemsg::pose1_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::plumbing_pub_sub_doublemsg::pose1_<ContainerAllocator1> & lhs, const ::plumbing_pub_sub_doublemsg::pose1_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace plumbing_pub_sub_doublemsg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::plumbing_pub_sub_doublemsg::pose1_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plumbing_pub_sub_doublemsg::pose1_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::plumbing_pub_sub_doublemsg::pose1_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::plumbing_pub_sub_doublemsg::pose1_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plumbing_pub_sub_doublemsg::pose1_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plumbing_pub_sub_doublemsg::pose1_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::plumbing_pub_sub_doublemsg::pose1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc153912f1453b708d221682bc23d9ac";
  }

  static const char* value(const ::plumbing_pub_sub_doublemsg::pose1_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcc153912f1453b70ULL;
  static const uint64_t static_value2 = 0x8d221682bc23d9acULL;
};

template<class ContainerAllocator>
struct DataType< ::plumbing_pub_sub_doublemsg::pose1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "plumbing_pub_sub_doublemsg/pose1";
  }

  static const char* value(const ::plumbing_pub_sub_doublemsg::pose1_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::plumbing_pub_sub_doublemsg::pose1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::plumbing_pub_sub_doublemsg::pose1_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::plumbing_pub_sub_doublemsg::pose1_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pose1_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::plumbing_pub_sub_doublemsg::pose1_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::plumbing_pub_sub_doublemsg::pose1_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLUMBING_PUB_SUB_DOUBLEMSG_MESSAGE_POSE1_H
