# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from plumbing_pub_sub_doublemsg/pose2.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import plumbing_pub_sub_doublemsg.msg

class pose2(genpy.Message):
  _md5sum = "4b494f3bb942b17882f6ddc15759053f"
  _type = "plumbing_pub_sub_doublemsg/pose2"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """pose1 vel
pose1 ang
================================================================================
MSG: plumbing_pub_sub_doublemsg/pose1
float32 x
float32 y
float32 z"""
  __slots__ = ['vel','ang']
  _slot_types = ['plumbing_pub_sub_doublemsg/pose1','plumbing_pub_sub_doublemsg/pose1']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       vel,ang

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(pose2, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.vel is None:
        self.vel = plumbing_pub_sub_doublemsg.msg.pose1()
      if self.ang is None:
        self.ang = plumbing_pub_sub_doublemsg.msg.pose1()
    else:
      self.vel = plumbing_pub_sub_doublemsg.msg.pose1()
      self.ang = plumbing_pub_sub_doublemsg.msg.pose1()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.vel.x, _x.vel.y, _x.vel.z, _x.ang.x, _x.ang.y, _x.ang.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.vel is None:
        self.vel = plumbing_pub_sub_doublemsg.msg.pose1()
      if self.ang is None:
        self.ang = plumbing_pub_sub_doublemsg.msg.pose1()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.vel.x, _x.vel.y, _x.vel.z, _x.ang.x, _x.ang.y, _x.ang.z,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.vel.x, _x.vel.y, _x.vel.z, _x.ang.x, _x.ang.y, _x.ang.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.vel is None:
        self.vel = plumbing_pub_sub_doublemsg.msg.pose1()
      if self.ang is None:
        self.ang = plumbing_pub_sub_doublemsg.msg.pose1()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.vel.x, _x.vel.y, _x.vel.z, _x.ang.x, _x.ang.y, _x.ang.z,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6f = None
def _get_struct_6f():
    global _struct_6f
    if _struct_6f is None:
        _struct_6f = struct.Struct("<6f")
    return _struct_6f
